# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_yield',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
