# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0002_auto_20170120_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='denom',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='numerator',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
